In [5]:
# Mlblr internship Assignment 2
import numpy as np
from scipy.special import expit as sigmoid
wh=np.random.random((4,3))
bh=np.random.random(3)
bho=np.zeros((3,3))
for i,y in enumerate(bh):
  bho[0,i]=bh[i]
  bho[1,i]=bh[i]
  bho[2,i]=bh[i]

print('bias params')
print(bho)

ip=np.ones([3,4])
ip[0,1]=ip[0,3]=ip[1,1]=ip[2,0]=ip[2,2]=0
out=np.zeros((3,3))
outb=np.zeros((3,3))
print(ip)
print(wh)
print("activations without bias")
out=ip.dot(wh)
print(out)
print("with bias")
outb= out + bho
print(outb)
print("activations")
print(sigmoid(outb))

bias params
[[0.36226653 0.7411616  0.95377377]
 [0.36226653 0.7411616  0.95377377]
 [0.36226653 0.7411616  0.95377377]]
[[1. 0. 1. 0.]
 [1. 0. 1. 1.]
 [0. 1. 0. 1.]]
[[0.14153104 0.43874315 0.57705681]
 [0.42327118 0.34286572 0.58564487]
 [0.30951577 0.18761019 0.75011718]
 [0.3288749  0.06256645 0.31763536]]
activations without bias
[[0.45104681 0.62635334 1.327174  ]
 [0.77992171 0.68891979 1.64480935]
 [0.75214608 0.40543217 0.90328022]]
with bias
[[0.81331333 1.36751494 2.28094777]
 [1.14218823 1.43008139 2.59858312]
 [1.11441261 1.14659377 1.857054  ]]
activations
[[0.69281511 0.79697836 0.9072868 ]
 [0.75808117 0.806914   0.93077034]
 [0.75295084 0.75888821 0.8649532 ]]
